sudo: required
dist: trusty
language: rust

matrix:
  include:
    # parallel builds for tests
    - rust: stable
      env: NAME=trust-dns-proto
           RUST_BACKTRACE=full
      script: 
        - scripts/run_tests_proto.sh

    - rust: stable
      env: NAME=trust-dns-client
           RUST_BACKTRACE=full
      script: 
        - scripts/run_tests_client.sh

    - rust: stable
      env: NAME=trust-dns-resolver
           RUST_BACKTRACE=full
      script: 
        - scripts/run_tests_resolver.sh

    - rust: stable
      env: NAME=trust-dns-server
           RUST_BACKTRACE=full
      script: 
        - scripts/run_tests_server.sh

    - rust: stable
      env: NAME=trust-dns-integration-tests
           RUST_BACKTRACE=full
      script: 
        - scripts/run_tests_integration_tests.sh

    # coverage reports
    - rust: stable
      env: NAME=kcov
           RUST_BACKTRACE=full
           RUN_KCOV=1
      scripts: 
        - scripts/run_kcov.sh

    # min rust version
    # - rust: 1.14.0
    - rust: beta
      env: NAME=beta
           RUST_BACKTRACE=full
      script: 
        - scripts/run_tests_proto.sh

    # macos
    - os: osx
      rust: stable
      env: NAME=macOS
           RUST_BACKTRACE=full
      script: 
        - scripts/run_tests_proto.sh

    # nightly
    - rust: nightly
      env: NAME=nightly
           RUST_BACKTRACE=full
      script: 
        - scripts/run_tests_proto.sh

    # clippy
    - rust: nightly
      env: RUST_BACKTRACE=full
      before_install:
        - cargo install clippy --force
      script:
        - scripts/run_clippy.sh

    - rust: nightly
      env: RUST_BACKTRACE=full
      before_install:
        - cargo install rustfmt-nightly --force
      script:
        - cargo fmt --all -- --write-mode=diff

    # compatiblity tests
    - rust: stable
      env: TDNS_BIND_PATH="../../bind-9.11.0-P1/bin/named/named"
           RUST_BACKTRACE=full
      before_install:
        - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then scripts/install_openssl_deb.sh; fi
        - scripts/install_bind.sh
      script:
        - cargo test --manifest-path compatibility-tests/Cargo.toml --no-default-features --features=bind

  allow_failures:
    - rust: nightly

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then scripts/install_openssl_deb.sh; fi

#script:
#  - scripts/run_tests.sh

#after_success: scripts/run_kcov.sh
